/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fnkshezgoggtupqqcsoa";

/** Fallback quando variáveis `VITE_*` não estão definidas (veja `env.ts`). */
export const embeddedPublicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZua3NoZXpnb2dndHVwcXFjc29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDYyMjYsImV4cCI6MjA2OTk4MjIyNn0.O67lXRZCu0hpyxvPYgdlGFK3geWxit6wXGKX7oE3J2k";